#!/bin/bash

#Skript mis annab paarisarvude summa vahemikus 1 kuni n

#Muutuja

summa=0

#Arvude tsükkel

for (( arv=1; arv<11; arv++ ))
do
	jaak=$(($arv % 2))
	if [ $jaak -eq 0 ]; then
		summa=$(($summa + $arv))
		echo $summa
	fi
done
echo "Arvude vahemikus 1 kuni 10 (kaasaarvatud) paarisarvude summa on: $summa"
#lõpp
