#!/bin/bash

#Skript annab vastavale numbrile kuu nimetuse

#Kuu numbri sisestus

echo -n "Sisesta kuu number (1-12): "
read kuu

#Kontroll, kas arv asub meie antud vahemikus

if ((kuu >= 1 && kuu <= 12)); then

#Kasutame case konstruktsiooni kuu nimetuse leidmiseks

	case $kuu in
		1) echo "See on jaanuar";;
		2) echo "See on veebruar";;
		3) echo "See on märts";;
		4) echo "See on aprill";;
		5) echo "See on mai";;
		6) echo "See on juuni";;
		7) echo "See on juuli";;
		8) echo "See on august";;
		9) echo "See on september";;
		10) echo "See on oktoober";;
		11) echo "See on november";;
		12) echo "See on detsember";;
	esac
else
	echo "Antud arv ei ole meie vahemikus"
fi
