#!/bin/bash

#Skript, mis küsib täisarvu ja väljastab, kas on paaris või mitte

#Kontrolitakse, kas käsureaparameetrite arv ei võrdu 1-ga
if [ $# -ne 1 ]; then
	echo "Käivita see skript koos arvuga, mille paarsust soovid kontrollida. Näiteks: $0 3"
else
	arv=$1

#Kontrollitakse paarsust
	if [ $((arv % 2)) -eq 0 ]; then
		echo "$arv on paaris"
	else
		echo "$arv on paaritu"
	fi
fi
